@TaskManager.Api_HostAddress = http://localhost:5271

POST {{TaskManager.Api_HostAddress}}/api/tasks
Content-Type: application/json

{
  "title": "",
  "description": "Test task",
  "status": 0,
  "dueAt": "2026-01-01T00:00:00Z"
}

###
